### ISSUE TITLE
如何实现滚动高度超出文档高度？

### ISSUE THREAD

**Issue by xbotao** [dongkuo/NiceMark#1]
你好，在NiceMark中看到你实现的滚动高度超出了文档高度，这非常有意义，不知道作者是如何实现的？
请指教

**Comment by derker94** [comment]
如果你用的是CodeMirror，加一个插件[scrollpastend.js](https://github.com/derker94/NiceMark/blob/master/src/js/lib/codemirror/scrollpastend.js)就好。如果不是，你为文档加一个padding-bottom就行了啊。

**Comment by dongkuo** [comment]
@xbotao 如果你用的是CodeMirror，加一个插件scrollpastend.js就好。如果不是，你为文档加一个padding-bottom就行了啊。

**Comment by xbotao** [comment]
Thanks！

发自我的 iPhone
