### ISSUE TITLE
文档云存储？

### ISSUE THREAD

**Issue by xbotao** [dongkuo/NiceMark#2]
不知对于文档云存储有没有合适的思路和想法？

**Comment by dongkuo** [comment]
@xbotao 这个主要就是解决本地文档如何与服务器中对应文档进行同步问题，另外还可以考虑支持记录文档的修改，能够进行版本管理。我最初的想法是直接用Git来做，省时省力。

PS：这个小项目是几年前做到了，当时确实没有找到满意的Markdown工具，所以自己简单实现了一个。现在重新看几年前写的代码，觉得很好笑:-)，没打算继续做下去了，因为找到了一个最好用（没有之一）的Markdown工具[Typora](https://www.typora.io/)，

**Comment by xbotao** [comment]
我也在用Typora，但是有时候需要修改一些自己需要的功能，就没法弄了
